header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: ByteDance Inc.

  paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'CREDITS'
    - '.gitignore'
    - '.licenserc.yaml'
    - '.github/*'
    - 'go.mod'
    - 'go.sum'

  comment: on-failure