blank_issues_enabled: true
contact_links:
  - name: Security Bug Report
    url: https://github.com/bytedance/gopkg/blob/develop/CONTRIBUTING.md#3-security-bugs
    about: |
      Please do not report the safe disclosure of bugs to public issues.
      Contact us by email (gopkg@bytedance.com)
