name: Question
description: Ask a question
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: What do you want to know?
    validations:
      required: true
