name: Minimal setup
on:
  push:
    branches:
      - foo

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull origin develop
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install benchmark tools
        run: |
          go get -u golang.org/x/perf/cmd/benchstat
          go get -u github.com/willabides/benchdiff/cmd/benchdiff
      - name: Run benchmark
        run: |
          benchdiff --base-ref develop --debug --benchstat-output=markdown
