name: Benchdiff

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/benchdiff'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'
      - run: git fetch origin develop
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: WillAbides/benchdiff-action@v0.3.3
        id: diff
        with:
          status_sha: ${{ github.sha }}
          status_name: text-bench-result
          status_on_degraded: neutral
          benchdiff_args: |
            --packages ./collection/skipset/
            --cpu=1
            --count=10
            --warmup-count=1
            --benchtime=10ms
            --tolerance=50
            --base-ref origin/develop
            --debug
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        id: couc
        with:
          issue-number: '${{ github.event.issue.number }}'
          body: |
            ## Benchdiff Results
            Benchmark Command: `${{ steps.diff.outputs.bench_command }}`
            HEAD: ${{ steps.diff.outputs.head_sha }}
            Base: ${{ steps.diff.outputs.base_sha }}
            Degraded: ${{ steps.diff.outputs.degraded_result }}

            <details>
            Results
            <summary></summary>
            ${{ steps.diff.outputs.benchstat_output }}
            </details>
      - name: Check outputs
        run: echo 'Comment ID - ${{ steps.couc.outputs.comment-id }}'
