name: Minimal setup
on:
  push:
    branches:
      - foo

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin develop
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: WillAbides/benchdiff-action@v0.3.3
        with:
          status_sha: ${{ github.sha }}
          status_name: text-bench-result
          status_on_degraded: neutral
          benchdiff_args: |
            --packages ./collection/skipset/
            --cpu=1
            --count=10
            --warmup-count=1
            --benchtime=10ms
            --tolerance=50
            --base-ref origin/develop
            --debug
      # - name: Install benchmark tools
      #   run: |
      #     go get -u golang.org/x/perf/cmd/benchstat
      #     go get -u github.com/willabides/benchdiff/cmd/benchdiff
      # - name: Run benchmark
      #   run: |
      #     benchdiff --base-ref origin/develop --debug --benchstat-output=markdown
