name: Benchdiff

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  # https://github.community/t/cancelling-rest-of-job-if-condition-is-met/18181
  trigger:
    name: Pull request comment trigger
    outputs:
      triggered: ${{ steps.output.outputs.triggered }}
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/benchdiff'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set output
        id: output
        run: |
          echo '::set-output name=triggered::${{ steps.check.outputs.triggered }}'

  benchdiff:
    name: Performance regression check
    needs: [trigger]
    if: needs.trigger.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    env:
      # The git ref to be used as benchmark baseline
      BASE_REF: develop
    steps:
      - uses: actions/checkout@v2
      - name: Checkout HEAD & BASE
        # https://github.com/actions/checkout/issues/331
        run: |
          git fetch origin ${{ env.BASE_REF }}
          gh pr checkout ${{ github.event.issue.number }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: WillAbides/benchdiff-action@v0.3.3
        id: diff
        with:
          status_sha: ${{ github.sha }}
          status_name: Benchdiff result
          status_on_degraded: neutral
          benchdiff_args: |
            --packages ./collection/skipset/
            --cpu=1
            --count=10
            --warmup-count=1
            --benchtime=10ms
            --tolerance=50
            --base-ref origin/${{ env.BASE_REF }}
            --debug
      - name: Create pull request comment
        uses: peter-evans/create-or-update-comment@v1
        id: couc
        with:
          issue-number: '${{ github.event.issue.number }}'
          body: |
            ## Benchdiff Results
            Benchmark Command: `${{ steps.diff.outputs.bench_command }}`
            HEAD: ${{ steps.diff.outputs.head_sha }}
            Base: ${{ steps.diff.outputs.base_sha }}
            Degraded: ${{ steps.diff.outputs.degraded_result }}

            <details>
            <summary>Results</summary>
            ${{ steps.diff.outputs.benchstat_output }}
            </details>
      - name: Check outputs
        run: |
          echo 'Comment ID - ${{ steps.couc.outputs.comment-id }}'
