name: Feishu Notification

on:
  pull_request:
    types: [opened]

jobs:
  trigger:
    name: Pull Request Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Feishu Message
        env:
          ACTIONS_FEISHU_TAG: v1.3.1
          INPUT_WEBHOOK: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          INPUT_MESSAGE_TYPE: post
          INPUT_TITLE: New Pull Peqeust
          INPUT_CONTENT: |
            @${{ github.event.pull_request.user.login }} opened pull request #${{ github.event.pull_request.number }}:

                ${{ github.event.pull_request.title }}
            
            See: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
